/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Dialog: typeof import('primevue/dialog')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    RaceDetails: typeof import('./src/components/RaceDetails.vue')['default']
    Races: typeof import('./src/components/Races.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tracks: typeof import('./src/components/Tracks.vue')['default']
  }
}
